# Day 2 · NumPy 基础(1/3)

目标:数组的创建、属性、形状变换、广播复习。

今日节奏:40min 学习 + 15min 动手 + 5min 自检(最后有清单)。

> 打开方式:JupyterLab(http://127.0.0.1:8888/lab)文件树里进 `ai-learning/练习/` 双击本文件,逐格 Shift+Enter。

In [1]:
import sys
import numpy as np

print("Python", sys.version.split()[0], "| numpy", np.__version__)
print("环境 OK!开始今天的练习 →")

Python 3.14.6 | numpy 2.5.2
环境 OK!开始今天的练习 →


## 任务 1:三种方式创建数组

学习提示(先自己猜,再运行):
- `np.arange(10)` → 0..9 的整数数组
- `np.zeros((3, 4))` → 3 行 4 列全 0
- `np.linspace(0, 1, 5)` → 从 0 到 1 均匀取 5 个数

把缺的两行补上,然后 Shift+Enter。

In [2]:
a1 = np.arange(10)
print("arange:", a1)

a2 = np.zeros((3, 4))          # TODO:补全,3行4列全0
print("zeros:\n", a2)

a3 = np.linspace(0, 1, 5)      # TODO:补全,0到1均匀5个数
print("linspace:", a3)

arange: [0 1 2 3 4 5 6 7 8 9]
zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
linspace: [0.   0.25 0.5  0.75 1.  ]


## 任务 2:查看数组的属性

数组(`ndarray`)自带四个常看属性:`shape`(形状)、`ndim`(维度数)、`size`(元素总数)、`dtype`(元素类型)。

对随机矩阵 `np.random.rand(3, 4)` 完成打印:

In [3]:
m = np.random.rand(3, 4)   # 3行4列,元素是0~1随机小数
print("矩阵:\n", m)
print("shape:", m.shape)
print("ndim:", m.ndim)
print("size:", m.size)
print("dtype:", m.dtype)

矩阵:
 [[0.11466421 0.65126518 0.96368113 0.49690094]
 [0.63469001 0.63805934 0.04583833 0.8192799 ]
 [0.12420356 0.1210006  0.11996164 0.72977792]]
shape: (3, 4)
ndim: 2
size: 12
dtype: float64


## 任务 3:形状变换

把一维数组 `np.arange(12)` 变成 3×4 矩阵,再变回一维:
- `reshape(3, 4)`:重排形状(元素个数必须一致,12 = 3×4)
- `M.T`:转置(行变列)
- `flatten()`:摊平回一维

In [4]:
v = np.arange(12)
M = v.reshape(3, 4)
print("reshape:", M.shape, "\n", M)
print("转置:\n", M.T)
print("flatten:", M.flatten())

reshape: (3, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
转置:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 任务 4:广播复习(昨天的坑)

`a` 形状 (2,3)。两个候选 `b`,哪个能直接相加?先心算再运行:
- `b1 = np.array([10, 20, 30])` → 形状 `(3,)`
- `b2 = np.array([[10], [20]])` → 形状 `(2,1)`

规则回忆:维度**从右往左**对齐,不相等时**其中一个必须是 1**。

In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b1 = np.array([10, 20, 30])   # 形状 (3,) → 和 a 的列对齐,行方向广播
b2 = np.array([[10], [20]])   # 形状 (2,1) → 和 a 的行对齐,列方向广播
print("a + b1(行广播):\n", a + b1)
print("a + b2(列广播):\n", a + b2)

a + b1(行广播):
 [[11 22 33]
 [14 25 36]]
a + b2(列广播):
 [[11 12 13]
 [24 25 26]]


## 任务 5:小挑战 🔥

生成 5×5 随机整数矩阵(0~99),然后完成四问:
1. 打印第 2 行(索引 1)
2. 打印第 3 列(索引 2)→ 用 `M[:, 2]`
3. 每行的和 → `M.sum(axis=1)`(提前认识 `axis`,以后天天见)
4. 全矩阵平均值 → `M.mean()`

In [6]:
M = np.random.randint(0, 100, size=(5, 5))
print(M)
print("第2行:", M[1])
print("第3列:", M[:, 2])
print("每行和(axis=1):", M.sum(axis=1))
print("平均值:", M.mean())

[[87 60  0 61 12]
 [94  4 96  8 27]
 [17 84 72 31 49]
 [33 80 28 34 58]
 [55 57 79  4 50]]
第2行: [94  4 96  8 27]
第3列: [ 0 96 72 28 79]
每行和(axis=1): [220 229 253 233 245]
平均值: 47.2


## 自检清单(5 问,答不上就回看今天的格子)

1. `np.arange(10)` 和 Python 自带 `range(10)` 的区别? → 前者生成 numpy 数组,能直接参与运算
2. `reshape(-1)` 里的 `-1` 是什么意思? → "自动算"那一维,比如 12 个元素 reshape(3, -1) 自动得 4
3. `a.T` 对一维数组做了什么? → 一维数组转置等于没变(它只有一维)
4. 广播规则一句话? → 维度右对齐,长度不等时必须有一个是 1
5. `axis=0` 和 `axis=1`? → axis=0 沿行方向(每列出一个结果);axis=1 沿列方向(每行出一个结果);对应 sum:axis=0 每列和,axis=1 每行和

## 📝 收盘动作

```bash
git add -A && git commit -m "day2: numpy basics" && git push
```

然后跟助手说"生成日志",或自己在 `学习日志/2026-08-20.md` 里补一句今天的一句话总结。